sudo: required
services:
  - docker

before_install:
  - docker build -t vikram276/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vikram276/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "dockers"
  env: "Dockers-env"
  bucket_name: "elasticbeanstalk-us-west-2-891377317087"
  bucket_path: "dockers"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
